import type { Metadata } from 'next'
import { createElement } from 'react'

export const metadata: Metadata = {
    title: 'Property Investment in Dubai | Income and Growth Guide',
      description: 'Learn how to assess property investment in Dubai by asset type, location, yield, ownership costs, financing, and exit strategy.',
        alternates: { canonical: '/insights/property-investment-in-dubai' },
}

      export const articleSchema = {
                '@context': 'https://schema.org',
                  '@type': 'Article',
                    headline: 'Property Investment in Dubai: Income and Growth Guide',
                      description: metadata.description,
                        author: { '@type': 'Person', name: 'Gopal Ahuja' },
                          publisher: { '@type': 'Organization', name: 'Gopal Ahuja', url: 'https://www.gopalahuja.com' },
                            mainEntityOfPage: 'https://www.gopalahuja.com/insights/property-investment-in-dubai',
      }

                    export const faqSchema = {
                                            '@context': 'https://schema.org',
                                              '@type': 'FAQPage',
                                                mainEntity: [
                                                  { '@type': 'Question', name: 'What is the best property investment in Dubai?', acceptedAnswer: { '@type': 'Answer', text: 'The best property depends on the objective. A completed unit may suit income, while an off-plan or development opportunity may suit a higher-growth and higher-risk strategy.' } },
                                                  { '@type': 'Question', name: 'How do I calculate Dubai property returns?', acceptedAnswer: { '@type': 'Answer', text: 'Calculate net returns after vacancy, service charges, management, maintenance, financing, purchase costs, and expected selling costs rather than using gross rent alone.' } },
                                                                                      ],
                    }

                                    const h = createElement
                                    const quickAnswer = 'Property investment in Dubai should be assessed through net income, potential value growth, ownership costs, and exit liquidity. Start by choosing the objective: stable rent, long-term appreciation, development upside, or portfolio diversification. Then compare locations and assets on consistent assumptions, verify the legal and physical facts, and stress-test the outcome if rents fall, costs rise, delivery is delayed, or the sale takes longer than planned.'
                                    const assets = [
                                                                            ['Studio or one-bedroom', 'Liquid rental demand in selected districts', 'Tenant profile, service charges, supply'],
                                                                              ['Villa or townhouse', 'Family demand and larger ticket exposure', 'Land component, maintenance, resale pool'],
                                                                                ['Office or retail', 'Commercial income and business demand', 'Occupancy, lease quality, fit-out cost'],
                                                                                  ['Off-plan', 'Staged payments and potential appreciation', 'Developer, delivery, handover, resale rules'],
                                                                                  ]
                                            const diligence = [
                                                                                            'Define target net yield, growth case, and minimum holding period.',
                                                                                              'Compare at least three relevant transactions and rental references.',
                                                                                                'Review title, contract, developer history, service charges, and condition.',
                                                                                                  'Build a cash-flow model with vacancy, costs, financing, and downside scenarios.',
                                                                                                    'Set an exit plan before purchase, including likely buyer and sale timeline.',
                                                                                                    ]

                                                      export default function Page() {
                                                                                                                return h('main', { className: 'mx-auto max-w-4xl px-6 py-20 text-slate-900' },
                                                                                                                                                                                     h('article', { className: 'prose prose-slate max-w-none' },
                                                                                                                                                                                                                                                         h('script', { type: 'application/ld+json', dangerouslySetInnerHTML: { __html: JSON.stringify(articleSchema) } }),
                                                                                                                                                                                                                                                               h('script', { type: 'application/ld+json', dangerouslySetInnerHTML: { __html: JSON.stringify(faqSchema) } }),
                                                                                                                                                                                                                                                                     h('p', { className: 'text-sm font-semibold uppercase tracking-widest text-red-700' }, 'Quick Answer'),
                                                                                                                                                                                                                                                                           h('p', { className: 'text-xl leading-8' }, quickAnswer),
                                                                                                                                                                                                                                                                                 h('h1', null, 'Property Investment in Dubai: Income and Growth Guide'),
                                                                                                                                                                                                                                                                                       h('h2', null, 'What should property investment in Dubai achieve?'),
                                                                                                                                                                                                                                                                                             h('p', null, 'A property can be an income asset, a growth asset, an operating business, or a diversification position. Write the desired outcome, acceptable volatility, leverage, and point at which the investment should be sold or refinanced.'),
                                                                                                                                                                                                                                                                                                   h('h2', null, 'Which Dubai property types should you compare?'),
                                                                                                                                                                                                                                                                                                         h('table', { className: 'w-full text-left' },
                                                                                                                                                                                                                                                                                                                                                                                                                                     h('thead', null, h('tr', null, h('th', null, 'Property type'), h('th', null, 'Potential role'), h('th', null, 'Key question'))),
                                                                                                                                                                                                                                                                                                                                                                                                                                             h('tbody', null, assets.map((row) => h('tr', { key: row[0] }, row.map((cell) => h('td', { key: cell }, cell)))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                         h('h2', null, 'How do you compare net property returns?'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                               h('p', null, 'Begin with realistic gross rent, then deduct vacancy, service charges, management, maintenance, insurance, financing, and other ownership costs. Separate recurring income from one-time acquisition costs and model the sale separately.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     h('h3', null, 'What diligence steps reduce avoidable risk?'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           h('ol', null, diligence.map((item) => h('li', { key: item }, item))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 h('h2', null, 'How should location influence the decision?'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       h('p', null, 'Location is a shorthand for demand, access, supply, amenity quality, and future competition. Examine who will rent or buy, why they choose the area, how much comparable stock is planned, and whether the asset remains attractive in a slower market.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             h('h2', null, 'What should a downside case include?'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   h('p', null, 'Model lower rent, higher vacancy, rising service charges, delayed completion, additional maintenance, higher borrowing cost, and a longer exit. If the investor cannot fund the downside period, reduce leverage, change the asset, or wait.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         h('p', null, h('a', { href: '/insights' }, 'Browse the real estate insights hub'), ' or ', h('a', { href: '/#contact' }, 'request a structured property review'), '.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ),
                                                                                                                                                                                                                                                                                                                                                                                           )
                                                                                                                                                                                                                                                                                                                             )
                                                      }
