import type { Metadata } from 'next'
import { createElement } from 'react'

export const metadata: Metadata = {
    title: 'Dubai Investment Properties | How to Choose an Asset',
      description: 'Compare Dubai investment properties by income, growth, location, ownership costs, tenant demand, and resale liquidity.',
        alternates: { canonical: '/insights/dubai-investment-properties' },
}

      export const articleSchema = {
                '@context': 'https://schema.org',
                  '@type': 'Article',
                    headline: 'Dubai Investment Properties: How to Choose an Asset',
                      description: metadata.description,
                        author: { '@type': 'Person', name: 'Gopal Ahuja' },
                          publisher: { '@type': 'Organization', name: 'Gopal Ahuja', url: 'https://www.gopalahuja.com' },
                            mainEntityOfPage: 'https://www.gopalahuja.com/insights/dubai-investment-properties',
      }

                    export const faqSchema = {
                                            '@context': 'https://schema.org',
                                              '@type': 'FAQPage',
                                                mainEntity: [
                                                  { '@type': 'Question', name: 'What are the best Dubai investment properties?', acceptedAnswer: { '@type': 'Answer', text: 'The best property is the one whose demand, price, net cash flow, risk, and exit route match the investor strategy.' } },
                                                  { '@type': 'Question', name: 'Should I buy a ready or off-plan property in Dubai?', acceptedAnswer: { '@type': 'Answer', text: 'Ready property offers observable condition and income, while off-plan may offer staged payments and growth potential with greater delivery risk.' } },
                                                                                      ],
                    }

                                    const h = createElement
                                    const quickAnswer = 'The right Dubai investment property depends on whether the goal is rental income, capital growth, development upside, or diversification. Compare ready and off-plan homes, villas, offices, retail, and land using the same framework: who creates demand, what is the all-in price, what is the net income, what can go wrong, and who will buy the asset when you exit. Evidence matters more than a generic list of hot areas.'
                                    const rows = [
                                                                            ['Ready apartment', 'Visible condition and current rent', 'Building quality, tenant demand, net yield'],
                                                                              ['Villa or townhouse', 'Family demand and larger land component', 'Maintenance, community, resale depth'],
                                                                                ['Off-plan residence', 'Staged payments and new-build appeal', 'Developer delivery, escrow, handover'],
                                                                                  ['Commercial asset', 'Business income and lease potential', 'Occupancy, tenant quality, fit-out'],
                                                                                  ]
                                            const checklist = [
                                                                                            'Clarify target return, risk budget, leverage, and hold period.',
                                                                                              'Identify the actual tenant or buyer and why they choose the location.',
                                                                                                'Calculate all-in cost, including fees, fit-out, service charges, and financing.',
                                                                                                  'Verify title, contracts, condition, developer track record, and comparable evidence.',
                                                                                                    'Plan the exit around liquidity, likely buyer, and realistic sale timing.',
                                                                                                    ]

                                                      export default function Page() {
                                                                                                                return h('main', { className: 'mx-auto max-w-4xl px-6 py-20 text-slate-900' },
                                                                                                                                                                                     h('article', { className: 'prose prose-slate max-w-none' },
                                                                                                                                                                                                                                                         h('script', { type: 'application/ld+json', dangerouslySetInnerHTML: { __html: JSON.stringify(articleSchema) } }),
                                                                                                                                                                                                                                                               h('script', { type: 'application/ld+json', dangerouslySetInnerHTML: { __html: JSON.stringify(faqSchema) } }),
                                                                                                                                                                                                                                                                     h('p', { className: 'text-sm font-semibold uppercase tracking-widest text-red-700' }, 'Quick Answer'),
                                                                                                                                                                                                                                                                           h('p', { className: 'text-xl leading-8' }, quickAnswer),
                                                                                                                                                                                                                                                                                 h('h1', null, 'Dubai Investment Properties: How to Choose an Asset'),
                                                                                                                                                                                                                                                                                       h('h2', null, 'What makes a Dubai property investable?'),
                                                                                                                                                                                                                                                                                             h('p', null, 'An investable property has a clear demand source, a price supported by comparable evidence, manageable ownership costs, and a credible exit route. The asset should still make sense after conservative assumptions for rent, vacancy, financing, maintenance, and the time required to sell.'),
                                                                                                                                                                                                                                                                                                   h('h2', null, 'Which Dubai investment properties should you compare?'),
                                                                                                                                                                                                                                                                                                         h('table', { className: 'w-full text-left' },
                                                                                                                                                                                                                                                                                                                                                                                                                                     h('thead', null, h('tr', null, h('th', null, 'Asset'), h('th', null, 'Potential advantage'), h('th', null, 'Main diligence focus'))),
                                                                                                                                                                                                                                                                                                                                                                                                                                             h('tbody', null, rows.map((row) => h('tr', { key: row[0] }, row.map((cell) => h('td', { key: cell }, cell)))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                         h('h2', null, 'How do you choose between ready and off-plan property?'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                               h('p', null, 'Ready property provides observable condition, current service-charge information, and a clearer view of achievable rent. Off-plan property can offer staged payments and a new building, but it adds developer, delivery, handover, and market-timing risk.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     h('h3', null, 'What should an investor check before reserving a property?'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           h('ol', null, checklist.map((item) => h('li', { key: item }, item))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 h('h2', null, 'How do location and building quality affect returns?'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       h('p', null, 'A strong location cannot fully rescue a poorly managed building, and an attractive building cannot create demand where access or tenant fit is weak. Review transport, amenities, competing supply, management, maintenance, service charges, and tenant profile together.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             h('h2', null, 'What should you do when two properties look similar?'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   h('p', null, 'Put both assets into the same cash-flow model. Compare net yield, downside cash need, expected holding period, resale pool, and the quality of the evidence behind each assumption. Prefer the property that remains robust when optimistic assumptions are removed.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         h('p', null, h('a', { href: '/insights' }, 'See more Dubai real estate insights'), ' or ', h('a', { href: '/#contact' }, 'discuss a property shortlist'), ' with Gopal Ahuja.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ),
                                                                                                                                                                                                                                                                                                                                                                                           )
                                                                                                                                                                                                                                                                                                                             )
                                                      }
