import type { Metadata } from 'next'
import { createElement } from 'react'

export const metadata: Metadata = {
    title: 'Why Invest in Dubai Real Estate? | Investor Case',
      description: 'Understand why investors consider Dubai real estate, from demand and infrastructure to ownership, income, growth, and risk.',
        alternates: { canonical: '/insights/why-invest-in-dubai-real-estate' },
}

      export const articleSchema = {
                '@context': 'https://schema.org',
                  '@type': 'Article',
                    headline: 'Why Invest in Dubai Real Estate? The Investor Case',
                      description: metadata.description,
                        author: { '@type': 'Person', name: 'Gopal Ahuja' },
                          publisher: { '@type': 'Organization', name: 'Gopal Ahuja', url: 'https://www.gopalahuja.com' },
                            mainEntityOfPage: 'https://www.gopalahuja.com/insights/why-invest-in-dubai-real-estate',
      }

                    export const faqSchema = {
                                            '@context': 'https://schema.org',
                                              '@type': 'FAQPage',
                                                mainEntity: [
                                                  { '@type': 'Question', name: 'Why do investors choose Dubai property?', acceptedAnswer: { '@type': 'Answer', text: 'Investors may choose Dubai for international demand, infrastructure, freehold ownership options, business connectivity, and a range of income and growth assets.' } },
                                                  { '@type': 'Question', name: 'What is the biggest risk of Dubai real estate?', acceptedAnswer: { '@type': 'Answer', text: 'The biggest risk is paying too much for an asset whose demand, income, or exit liquidity does not support the investment case.' } },
                                                                                      ],
                    }

                                    const h = createElement
                                    const quickAnswer = 'Investors consider Dubai real estate because the city combines international connectivity, a growing population and business base, established freehold districts, and a wide range of residential and commercial assets. Those advantages do not guarantee returns. The investment case becomes credible only when demand, price, income, financing, ownership costs, regulation, and exit liquidity are tested for a specific property.'
                                    const reasons = [
                                                                            'International tenant and buyer demand can create multiple demand sources.',
                                                                              'Infrastructure and business activity can support long-term location quality.',
                                                                                'Freehold areas offer defined ownership opportunities for eligible buyers.',
                                                                                  'The market includes assets for income, growth, development, and diversification.',
                                                                                  ]
                                            const comparison = [
                                                                                            ['Income focus', 'Completed, lettable property', 'Rent, vacancy, service charges'],
                                                                                              ['Growth focus', 'Well-located development or off-plan', 'Entry price, delivery, comparable sales'],
                                                                                                ['Diversification focus', 'Distinct Dubai exposure', 'Currency, concentration, liquidity'],
                                                                                                ]

                                                  export default function Page() {
                                                                                                        return h('main', { className: 'mx-auto max-w-4xl px-6 py-20 text-slate-900' },
                                                                                                                                                                         h('article', { className: 'prose prose-slate max-w-none' },
                                                                                                                                                                                                                                         h('script', { type: 'application/ld+json', dangerouslySetInnerHTML: { __html: JSON.stringify(articleSchema) } }),
                                                                                                                                                                                                                                               h('script', { type: 'application/ld+json', dangerouslySetInnerHTML: { __html: JSON.stringify(faqSchema) } }),
                                                                                                                                                                                                                                                     h('p', { className: 'text-sm font-semibold uppercase tracking-widest text-red-700' }, 'Quick Answer'),
                                                                                                                                                                                                                                                           h('p', { className: 'text-xl leading-8' }, quickAnswer),
                                                                                                                                                                                                                                                                 h('h1', null, 'Why Invest in Dubai Real Estate? The Investor Case'),
                                                                                                                                                                                                                                                                       h('h2', null, 'What makes Dubai relevant to international investors?'),
                                                                                                                                                                                                                                                                             h('p', null, 'Dubai is both a city and a cross-border market. Investors assess it for regional business flows, a globally connected population, tourism and employment demand, and a property ecosystem spanning apartments, villas, offices, retail, land, and development. Each benefit must be matched to an asset and a price.'),
                                                                                                                                                                                                                                                                                   h('h2', null, 'Which investment reasons matter most?'),
                                                                                                                                                                                                                                                                                         h('ol', null, reasons.map((reason) => h('li', { key: reason }, reason))),
                                                                                                                                                                                                                                                                                               h('h2', null, 'How should you match the rationale to an asset?'),
                                                                                                                                                                                                                                                                                                     h('table', { className: 'w-full text-left' },
                                                                                                                                                                                                                                                                                                                                                                                                                                         h('thead', null, h('tr', null, h('th', null, 'Investor rationale'), h('th', null, 'Possible asset approach'), h('th', null, 'What to test'))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                 h('tbody', null, comparison.map((row) => h('tr', { key: row[0] }, row.map((cell) => h('td', { key: cell }, cell)))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                             h('h3', null, 'Can Dubai property provide both income and growth?'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   h('p', null, 'Some assets can offer both, but the balance changes by location, building quality, entry price, financing, and market cycle. Underwrite rent separately from price movement and do not use appreciation to compensate for a weak operating case.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         h('h2', null, 'What risks should an investor challenge?'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               h('p', null, 'Challenge concentration, optimistic rents, service charges, completion timing, developer exposure, interest rates, currency movement, and the time required to sell. Ask what happens if the property takes longer to lease or sell than expected.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     h('h2', null, 'How can an investor make the decision responsibly?'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           h('ol', null, ['Write the objective before viewing properties.', 'Use comparable evidence to separate value from asking price.', 'Model total ownership cost and downside cash needs.', 'Confirm legal, technical, title, and operating information independently.'].map((item) => h('li', { key: item }, item))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 h('p', null, h('a', { href: '/insights' }, 'Read the full insights hub'), ' or ', h('a', { href: '/#contact' }, 'speak with Gopal Ahuja'), '.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ),
                                                                                                                                                                                                                                                                                                                                                                           )
                                                                                                                                                                                                                                                                                                                 )
                                                  }
